ALTER TABLE users
ADD COLUMN age INT NULL,
ADD COLUMN height FLOAT NULL,
ADD COLUMN weight FLOAT NULL,
ADD COLUMN ranking VARCHAR(50) NULL,
ADD COLUMN mean_global_ranking VARCHAR(50) NULL,
ADD COLUMN profile_image VARCHAR(255) NULL;
